/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brahvim_physics_SpContext */

#ifndef _Included_com_brahvim_physics_SpContext
#define _Included_com_brahvim_physics_SpContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brahvim_physics_SpContext
 * Method:    getCtxRot
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContext_getCtxRot
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContext
 * Method:    getCtxTrans
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContext_getCtxTrans
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContext
 * Method:    getCapacityMasses
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContext_getCapacityMasses
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContext
 * Method:    getMaxId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContext_getMaxId
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContext
 * Method:    getMasses
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContext_getMasses__
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContext
 * Method:    getMasses
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SpContext_getMasses__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContext
 * Method:    setCtxRot
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContext_setCtxRot
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContext
 * Method:    setCtxTrans
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContext_setCtxTrans
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContext
 * Method:    setCapacityMasses
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContext_setCapacityMasses
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContext
 * Method:    setMaxId
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContext_setMaxId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContext
 * Method:    setMasses
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContext_setMasses__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContext
 * Method:    setMasses
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContext_setMasses__JF
  (JNIEnv *, jobject, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
