/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brahvim_physics_SpSolverParametersRotation */

#ifndef _Included_com_brahvim_physics_SpSolverParametersRotation
#define _Included_com_brahvim_physics_SpSolverParametersRotation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brahvim_physics_SpSolverParametersRotation
 * Method:    getAngles
 * Signature: ()Lcom/brahvim/physics/SpVec3;
 */
JNIEXPORT jobject JNICALL Java_com_brahvim_physics_SpSolverParametersRotation_getAngles
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpSolverParametersRotation
 * Method:    getAngularVelocity
 * Signature: ()Lcom/brahvim/physics/SpVec3;
 */
JNIEXPORT jobject JNICALL Java_com_brahvim_physics_SpSolverParametersRotation_getAngularVelocity
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpSolverParametersRotation
 * Method:    getAngularAcceleration
 * Signature: ()Lcom/brahvim/physics/SpVec3;
 */
JNIEXPORT jobject JNICALL Java_com_brahvim_physics_SpSolverParametersRotation_getAngularAcceleration
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpSolverParametersRotation
 * Method:    setAngles
 * Signature: (Lcom/brahvim/physics/SpVec3;)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpSolverParametersRotation_setAngles
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_brahvim_physics_SpSolverParametersRotation
 * Method:    setAngularVelocity
 * Signature: (Lcom/brahvim/physics/SpVec3;)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpSolverParametersRotation_setAngularVelocity
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_brahvim_physics_SpSolverParametersRotation
 * Method:    setAngularAcceleration
 * Signature: (Lcom/brahvim/physics/SpVec3;)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpSolverParametersRotation_setAngularAcceleration
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
