/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brahvim_physics_SpContextTranslation */

#ifndef _Included_com_brahvim_physics_SpContextTranslation
#define _Included_com_brahvim_physics_SpContextTranslation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    setCapacityInactive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextTranslation_setCapacityInactive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    setCapacityActive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextTranslation_setCapacityActive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    setCountInactive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextTranslation_setCountInactive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    setCountActive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextTranslation_setCountActive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    setInactive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextTranslation_setInactive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    setActive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextTranslation_setActive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    setData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextTranslation_setData__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    setData
 * Signature: (JLcom/brahvim/physics/SpSolverParametersTranslation;)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextTranslation_setData__JLcom_brahvim_physics_SpSolverParametersTranslation_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    getCapacityInactive
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContextTranslation_getCapacityInactive
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    getCapacityActive
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContextTranslation_getCapacityActive
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    getCountInactive
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContextTranslation_getCountInactive
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    getCountActive
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContextTranslation_getCountActive
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    getInactive
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContextTranslation_getInactive
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    getActive
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContextTranslation_getActive
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    getData
 * Signature: (J)Lcom/brahvim/physics/SpSolverParametersTranslation;
 */
JNIEXPORT jobject JNICALL Java_com_brahvim_physics_SpContextTranslation_getData__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextTranslation
 * Method:    getData
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContextTranslation_getData__
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
