/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brahvim_physics_SpContextRotation */

#ifndef _Included_com_brahvim_physics_SpContextRotation
#define _Included_com_brahvim_physics_SpContextRotation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    setCapacityInactive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextRotation_setCapacityInactive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    setCapacityActive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextRotation_setCapacityActive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    setCountInactive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextRotation_setCountInactive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    setCountActive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextRotation_setCountActive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    setInactive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextRotation_setInactive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    setActive
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextRotation_setActive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    setData
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextRotation_setData__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    setData
 * Signature: (JLcom/brahvim/physics/SpSolverParametersRotation;)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SpContextRotation_setData__JLcom_brahvim_physics_SpSolverParametersRotation_2
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    getCapacityInactive
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContextRotation_getCapacityInactive
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    getCapacityActive
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContextRotation_getCapacityActive
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    getCountInactive
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContextRotation_getCountInactive
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    getCountActive
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContextRotation_getCountActive
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    getInactive
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContextRotation_getInactive
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    getActive
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContextRotation_getActive
  (JNIEnv *, jobject);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    getData
 * Signature: (J)Lcom/brahvim/physics/SpSolverParametersRotation;
 */
JNIEXPORT jobject JNICALL Java_com_brahvim_physics_SpContextRotation_getData__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SpContextRotation
 * Method:    getData
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SpContextRotation_getData__
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
