/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brahvim_physics_SimplePhysics */

#ifndef _Included_com_brahvim_physics_SimplePhysics
#define _Included_com_brahvim_physics_SimplePhysics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_test
  (JNIEnv *, jclass);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    getMacroValuePhysicsErrorNone
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SimplePhysics_getMacroValuePhysicsErrorNone
  (JNIEnv *, jclass);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    getMacroValuePhysicsErrorObjectNull
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SimplePhysics_getMacroValuePhysicsErrorObjectNull
  (JNIEnv *, jclass);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    getMacroValuePhysicsErrorOutOfMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SimplePhysics_getMacroValuePhysicsErrorOutOfMemory
  (JNIEnv *, jclass);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    getMacroValuePhysicsErrorObjectAbsent
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SimplePhysics_getMacroValuePhysicsErrorObjectAbsent
  (JNIEnv *, jclass);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    contextAlloc
 * Signature: ()Lcom/brahvim/physics/SpResultPointer;
 */
JNIEXPORT jobject JNICALL Java_com_brahvim_physics_SimplePhysics_contextAlloc
  (JNIEnv *, jclass);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    contextFree
 * Signature: (Lcom/brahvim/physics/SpContext;)J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SimplePhysics_contextFree
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyDestroy
 * Signature: (Lcom/brahvim/physics/SpContext;J)J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SimplePhysics_bodyDestroy
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyCreate
 * Signature: (Lcom/brahvim/physics/SpContext;)Lcom/brahvim/physics/SpResultInteger;
 */
JNIEXPORT jobject JNICALL Java_com_brahvim_physics_SimplePhysics_bodyCreate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    solveTranslationEuler
 * Signature: (Lcom/brahvim/physics/SpContextTranslation;F)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_solveTranslationEuler
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    solveTranslationVerlet
 * Signature: (Lcom/brahvim/physics/SpContextTranslation;F)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_solveTranslationVerlet
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    contextTranslationAlloc
 * Signature: ()Lcom/brahvim/physics/SpResultPointer;
 */
JNIEXPORT jobject JNICALL Java_com_brahvim_physics_SimplePhysics_contextTranslationAlloc
  (JNIEnv *, jclass);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    contextTranslationFree
 * Signature: (Lcom/brahvim/physics/SpContextTranslation;)J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SimplePhysics_contextTranslationFree
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    contextTranslationCreateEntry
 * Signature: (Lcom/brahvim/physics/SpContextTranslation;J)J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SimplePhysics_contextTranslationCreateEntry
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    contextTranslationDestroyEntry
 * Signature: (Lcom/brahvim/physics/SpContextTranslation;J)J
 */
JNIEXPORT jlong JNICALL Java_com_brahvim_physics_SimplePhysics_contextTranslationDestroyEntry
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetMass
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetMass
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetPosX
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetPosX
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetPosY
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetPosY
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetPosZ
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetPosZ
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetPos
 * Signature: (Lcom/brahvim/physics/SpContext;J)Lcom/brahvim/physics/SpVec3;
 */
JNIEXPORT jobject JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetPos
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetVelX
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetVelX
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetVelY
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetVelY
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetVelZ
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetVelZ
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetVel
 * Signature: (Lcom/brahvim/physics/SpContext;J)Lcom/brahvim/physics/SpVec3;
 */
JNIEXPORT jobject JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetVel
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetAccX
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetAccX
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetAccY
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetAccY
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetAccZ
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetAccZ
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetAcc
 * Signature: (Lcom/brahvim/physics/SpContext;J)Lcom/brahvim/physics/SpVec3;
 */
JNIEXPORT jobject JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetAcc
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetAngX
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetAngX
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetAngY
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetAngY
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetAngZ
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetAngZ
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetVelAngX
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetVelAngX
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetVelAngY
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetVelAngY
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetVelAngZ
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetVelAngZ
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetAccAngX
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetAccAngX
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetAccAngY
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetAccAngY
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyGetAccAngZ
 * Signature: (Lcom/brahvim/physics/SpContext;J)F
 */
JNIEXPORT jfloat JNICALL Java_com_brahvim_physics_SimplePhysics_bodyGetAccAngZ
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetMass
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetMass
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetPosX
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetPosX
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetPosY
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetPosY
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetPosZ
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetPosZ
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetPosition
 * Signature: (Lcom/brahvim/physics/SpContext;JFFF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetPosition
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetVelX
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetVelX
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetVelY
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetVelY
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetVelZ
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetVelZ
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetVelocity
 * Signature: (Lcom/brahvim/physics/SpContext;JFFF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetVelocity
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetAccX
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetAccX
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetAccY
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetAccY
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetAccZ
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetAccZ
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetAcceleration
 * Signature: (Lcom/brahvim/physics/SpContext;JFFF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetAcceleration
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetAngX
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetAngX
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetAngY
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetAngY
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetAngZ
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetAngZ
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetAngles
 * Signature: (Lcom/brahvim/physics/SpContext;JFFF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetAngles
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetVelAngX
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetVelAngX
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetVelAngY
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetVelAngY
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetVelAngZ
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetVelAngZ
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetVelocityAngular
 * Signature: (Lcom/brahvim/physics/SpContext;JFFF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetVelocityAngular
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetAccAngX
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetAccAngX
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetAccAngY
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetAccAngY
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetAccAngZ
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetAccAngZ
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodySetAccelerationAngular
 * Signature: (Lcom/brahvim/physics/SpContext;JFFF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodySetAccelerationAngular
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddMass
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddMass
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddPosX
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddPosX
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddPosY
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddPosY
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddPosZ
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddPosZ
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddPosition
 * Signature: (Lcom/brahvim/physics/SpContext;JFFF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddPosition
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddVelX
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddVelX
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddVelY
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddVelY
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddVelZ
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddVelZ
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddVelocity
 * Signature: (Lcom/brahvim/physics/SpContext;JFFF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddVelocity
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddAccX
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddAccX
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddAccY
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddAccY
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddAccZ
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddAccZ
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddAcceleration
 * Signature: (Lcom/brahvim/physics/SpContext;JFFF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddAcceleration
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddAngX
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddAngX
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyAddAngY
 * Signature: (Lcom/brahvim/physics/SpContext;JF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyAddAngY
  (JNIEnv *, jclass, jobject, jlong, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyForceCenter
 * Signature: (Lcom/brahvim/physics/SpContext;JFFF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyForceCenter
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     com_brahvim_physics_SimplePhysics
 * Method:    bodyForce
 * Signature: (Lcom/brahvim/physics/SpContext;JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_SimplePhysics_bodyForce
  (JNIEnv *, jclass, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
