/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_brahvim_physics_Engine */

#ifndef _Included_com_brahvim_physics_Engine
#define _Included_com_brahvim_physics_Engine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_brahvim_physics_Engine
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_brahvim_physics_Engine_create
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
